# Generated by Django 3.1.1 on 2020-10-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
    ]
