# Generated by Django 3.1.1 on 2020-10-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_auto_20201001_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('church', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('check_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
