# Generated by Django 3.1.1 on 2020-10-02 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_auto_20201002_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userregister',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
